name = "Squad Music Radio"
author = "DarkShadow"
prefix = "SMRA"
mainprefix = "z"

[lint.sqf]
enabled = true # Default: true
exclude = [
]

# Launched with `hemtt launch`
[hemtt.launch.default]
workshop = [
    "450814997", # CBA_A3's Workshop ID
    "463939057", # Ace Workshop ID
]